#
# iRODS Consumer Image.
#
FROM ubuntu:18.04

# TODO: Remove this line when apt gets its stuff together
#RUN sed --in-place --regexp-extended "s/(\/\/)(archive\.ubuntu)/\1nl.\2/" /etc/apt/sources.list

RUN apt-get update && \
    apt-get install -y sudo wget less lsb-release apt-transport-https netcat gnupg2

RUN wget -qO - https://packages.irods.org/irods-signing-key.asc | apt-key add -; \
    echo "deb [arch=amd64] https://packages.irods.org/apt/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/renci-irods.list; \
    apt-get update && \
    apt-get install -y irods-runtime=4.2.12-1~bionic irods-icommands=4.2.12-1~bionic irods-server=4.2.12-1~bionic

EXPOSE 1247 1248

# Set command to execute when launching the container.
ADD start_consumer.sh irods_consumer.input /
RUN chmod u+x /start_consumer.sh
ENTRYPOINT ["./start_consumer.sh"]
