#
# iRODS Provider Image.
#
FROM ubuntu:18.04

# TODO: Remove this line when apt gets its stuff together
#RUN sed --in-place --regexp-extended "s/(\/\/)(archive\.ubuntu)/\1nl.\2/" /etc/apt/sources.list

ENV DEBIAN_FRONTEND=noninteractive

# Install pre-requisites
RUN apt-get update && \
    apt-get install -y sudo wget lsb-release apt-transport-https postgresql vim python-pip libfuse2 unixodbc rsyslog less gnupg2 && \
    pip install xmlrunner

# Setup catalog database
ADD db_commands.txt /
RUN service postgresql start && su - postgres -c 'psql -f /db_commands.txt'

RUN wget -qO - https://packages.irods.org/irods-signing-key.asc | apt-key add -; \
    echo "deb [arch=amd64] https://packages.irods.org/apt/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/renci-irods.list; \
    apt-get update && \
    apt-get install -y irods-runtime=4.2.12-1~bionic irods-icommands=4.2.12-1~bionic irods-server=4.2.12-1~bionic irods-database-plugin-postgres=4.2.12-1~bionic

EXPOSE 1247 1248

ADD for-etc-irods /

# Set command to execute when launching the container.
ADD start_provider.sh /
ADD testsetup-consortium.sh /
RUN chmod +x /testsetup-consortium.sh
RUN chmod u+x /start_provider.sh
ENTRYPOINT ["./start_provider.sh"]
